# Generated by Django 3.1.4 on 2021-01-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210108_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='for_anonymous_user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='in_order',
        ),
    ]
