# Generated by Django 3.1.4 on 2021-01-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210110_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_products',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
